name: VJesusBucket
api: 5.0.0
author: VennVDev
main: vennv\vjesusbucket\VJesusBucket
version: 1.0.1

commands:
  vjesusbucket:
    description: VJesusBucket command
    usage: /vjesusbucket give <player> <type> <amount>
    aliases: [vjb]
    permission: vjesusbucket.command
    permission-message: You don't have permission to use this command.

permissions:
  vjesusbucket.command:
    description: VJesusBucket command permission
    default: op